name: pd_paty_tickets
description: A party tickets controller.

version: 1.0.0+1

environment:
  sdk: ">=2.0.0-dev.68.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  qrcode_reader: ^0.4.4
  flutter_flux: ^4.1.3
  intl: ^0.15.7
  audioplayers: ^0.10.0
  global_configuration: any
  http: any
  http_middleware: any
  flutter_secure_storage: any
  cupertino_icons: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/alert.mp3
    - assets/cfg/